# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "g5k" do |g5k, override|
    override.nfs.functional = false
    g5k.project_id = "vagrant-g5k-example-gitlab"
    g5k.site = "rennes"
    g5k.username = "msimonin"
    g5k.gateway = "access.grid5000.fr"
    g5k.walltime = "02:00:00"
    g5k.image = {
      :path    => "/home/msimonin/public/debian-8.7-amd64-bento.qcow2",
      :backing => "snapshot"
    }
    g5k.net = {
      :type => "bridge",
    }
    g5k.oar = "virtual != 'None'"
  end #g5k
  config.ssh.insert_key = false

  # server machine
  config.vm.define "server" do |server|
    server.vm.box = "debian/contrib-jessie64"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.42.3"
    server.vm.synced_folder ".", "/vagrant", type: "rsync", disabled: true

    server.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.cpus = 1
    end

    server.vm.provision :ansible do |ansible|
      # Disable default limit to connect to all the machines
      ansible.playbook = "main.yml"
      ansible.raw_arguments = ["-vvv"]
    end

  end
end
